version = 1

[[analyzers]]
name = "csharp"

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  environment = ["browser"]

[[transformers]]
name = "prettier"

[[transformers]]
name = "standardjs"

[[transformers]]
name = "dotnet-format"