// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VLISSIDES.Data;

#nullable disable

namespace VLISSIDES.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231004204920_feuilleExcel")]
    partial class feuilleExcel
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("LivrePromotions", b =>
                {
                    b.Property<string>("LivresId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PromotionsId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LivresId", "PromotionsId");

                    b.HasIndex("PromotionsId");

                    b.ToTable("LivrePromotions");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "0",
                            ConcurrencyStamp = "706f1b7e-4122-480f-a45b-9c5768959648",
                            Name = "Employe",
                            NormalizedName = "EMPLOYE"
                        },
                        new
                        {
                            Id = "1",
                            ConcurrencyStamp = "ebb08d38-75dd-4034-a6db-c47b5ee9ffd3",
                            Name = "Membre",
                            NormalizedName = "MEMBRE"
                        },
                        new
                        {
                            Id = "2",
                            ConcurrencyStamp = "a47224ef-08f8-4154-b0a1-895dd5d82cb3",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "1",
                            RoleId = "0"
                        },
                        new
                        {
                            UserId = "2",
                            RoleId = "1"
                        },
                        new
                        {
                            UserId = "0",
                            RoleId = "2"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("VLISSIDES.Models.Adresse", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ApplicationUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CodePostal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoCivique")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pays")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UtilisateurLivraisonId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UtilisateurPrincipalId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ville")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.ToTable("Adresses");
                });

            modelBuilder.Entity("VLISSIDES.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("AdressePrincipaleId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("AdressePrincipaleId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasDiscriminator<string>("Discriminator").HasValue("ApplicationUser");

                    b.HasData(
                        new
                        {
                            Id = "0",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "cd7c15a9-4d9e-4757-9aa8-2ef34fd9f29d",
                            Email = "admin@admin.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Nom = "ADMIN",
                            NormalizedEmail = "ADMIN@ADMIN.COM",
                            NormalizedUserName = "ADMIN@ADMIN.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEP5A0+Sh49GqZJZev/DKqD7yieTvqVejrmGV0mV6PL5KNos4tLJnJL1tHceX7HezGA==",
                            PhoneNumberConfirmed = false,
                            Prenom = "Admin",
                            SecurityStamp = "de3729eb-68b8-49b7-bb7b-3675b8d7c711",
                            TwoFactorEnabled = false,
                            UserName = "admin@admin.com"
                        });
                });

            modelBuilder.Entity("VLISSIDES.Models.Auteur", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("NomAuteur")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Auteurs", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "Excel 1",
                            NomAuteur = "Antoine de Saint-Exupéry"
                        },
                        new
                        {
                            Id = "Excel 2",
                            NomAuteur = "J.K. Rowling"
                        },
                        new
                        {
                            Id = "Excel 3",
                            NomAuteur = "George Orwell"
                        },
                        new
                        {
                            Id = "Excel 4",
                            NomAuteur = "J.R.R. Tolkien"
                        },
                        new
                        {
                            Id = "Excel 5",
                            NomAuteur = "Umberto Eco"
                        },
                        new
                        {
                            Id = "Excel 6",
                            NomAuteur = "Jane Austen"
                        },
                        new
                        {
                            Id = "Excel 7",
                            NomAuteur = "Boris Vian"
                        },
                        new
                        {
                            Id = "Excel 8",
                            NomAuteur = "Victor Hugo"
                        },
                        new
                        {
                            Id = "Excel 9",
                            NomAuteur = "Stendhal"
                        },
                        new
                        {
                            Id = "Excel 10",
                            NomAuteur = "René Barjavel"
                        },
                        new
                        {
                            Id = "Excel 11",
                            NomAuteur = "Giuseppe Tomasi di Lampedusa"
                        },
                        new
                        {
                            Id = "Excel 12",
                            NomAuteur = "Bernard Werber"
                        },
                        new
                        {
                            Id = "Excel 13",
                            NomAuteur = "Herman Melville"
                        },
                        new
                        {
                            Id = "Excel 14",
                            NomAuteur = "Fiodor Dostoïevski"
                        },
                        new
                        {
                            Id = "Excel 15",
                            NomAuteur = "Mikhaïl Boulgakov"
                        },
                        new
                        {
                            Id = "Excel 16",
                            NomAuteur = "Patrick Süskind"
                        },
                        new
                        {
                            Id = "Excel 17",
                            NomAuteur = "Joseph Kessel"
                        },
                        new
                        {
                            Id = "Excel 18",
                            NomAuteur = "Albert Camus"
                        },
                        new
                        {
                            Id = "Excel 19",
                            NomAuteur = "Donna Tartt"
                        },
                        new
                        {
                            Id = "Excel 20",
                            NomAuteur = "Anne Frank"
                        },
                        new
                        {
                            Id = "Excel 22",
                            NomAuteur = "Homère"
                        },
                        new
                        {
                            Id = "Excel 23",
                            NomAuteur = "Ernest Hemingway"
                        },
                        new
                        {
                            Id = "Excel 24",
                            NomAuteur = "Helen Fielding"
                        },
                        new
                        {
                            Id = "Excel 25",
                            NomAuteur = "Aldous Huxley"
                        },
                        new
                        {
                            Id = "Excel 26",
                            NomAuteur = "Paulo Coelho"
                        },
                        new
                        {
                            Id = "Excel 27",
                            NomAuteur = "Oscar Wilde"
                        },
                        new
                        {
                            Id = "Excel 28",
                            NomAuteur = "Alexandre Dumas"
                        },
                        new
                        {
                            Id = "Excel 31",
                            NomAuteur = "Khaled Hosseini"
                        },
                        new
                        {
                            Id = "Excel 32",
                            NomAuteur = "Alain-Fournier"
                        },
                        new
                        {
                            Id = "Excel 33",
                            NomAuteur = "Kurt Cobain"
                        },
                        new
                        {
                            Id = "Excel 34",
                            NomAuteur = "Charles Baudelaire"
                        },
                        new
                        {
                            Id = "Excel 35",
                            NomAuteur = "Francis Ponge"
                        },
                        new
                        {
                            Id = "Excel 36",
                            NomAuteur = "Frères Grimm"
                        },
                        new
                        {
                            Id = "Excel 37",
                            NomAuteur = "Charles Perrault"
                        },
                        new
                        {
                            Id = "Excel 38",
                            NomAuteur = "Hans Christian Andersen"
                        },
                        new
                        {
                            Id = "Excel 39",
                            NomAuteur = "Anonyme (contes populaires)"
                        },
                        new
                        {
                            Id = "Excel 40",
                            NomAuteur = "Pierre Gripari"
                        },
                        new
                        {
                            Id = "Excel 42",
                            NomAuteur = "Catherine Gueguen"
                        },
                        new
                        {
                            Id = "Excel 43",
                            NomAuteur = "Pierre Rabhi"
                        },
                        new
                        {
                            Id = "Excel 44",
                            NomAuteur = "Audrey Akoun et Isabelle Pailleau"
                        },
                        new
                        {
                            Id = "Excel 45",
                            NomAuteur = "Anne Bérubé & Geneviève Racine"
                        },
                        new
                        {
                            Id = "Excel 46",
                            NomAuteur = "Audrey Zucchi"
                        },
                        new
                        {
                            Id = "Excel 48",
                            NomAuteur = "René Goscinny"
                        },
                        new
                        {
                            Id = "Excel 49",
                            NomAuteur = "Hergé"
                        },
                        new
                        {
                            Id = "Excel 50",
                            NomAuteur = "Art Spiegelman"
                        },
                        new
                        {
                            Id = "Excel 51",
                            NomAuteur = "Marjane Satrapi"
                        },
                        new
                        {
                            Id = "Excel 52",
                            NomAuteur = "Alan Moore"
                        },
                        new
                        {
                            Id = "0",
                            NomAuteur = "Tony"
                        });
                });

            modelBuilder.Entity("VLISSIDES.Models.Categorie", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ParentId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("Categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "Excel 34",
                            Description = "",
                            Nom = "Poésie"
                        },
                        new
                        {
                            Id = "Excel 42",
                            Description = "",
                            Nom = "Pédagogie"
                        },
                        new
                        {
                            Id = "Excel 43",
                            Description = "",
                            Nom = "Maternité"
                        },
                        new
                        {
                            Id = "Excel 48",
                            Description = "",
                            Nom = "BD"
                        },
                        new
                        {
                            Id = "1",
                            Description = "Une section dédiée à l'exploration des chefs-d'œuvre artistiques, des mouvements et des artistes qui ont marqué l'histoire.",
                            Nom = "Art"
                        },
                        new
                        {
                            Id = "2",
                            Description = "Plongez dans un monde de bien-être, d'esthétique et d'équilibre pour enrichir votre quotidien.",
                            Nom = "Art de vivre"
                        },
                        new
                        {
                            Id = "3",
                            Description = "De colorées bandes dessinées aux histoires captivantes pour les plus jeunes, sans oublier une touche d'humour.",
                            Nom = "BD, Jeunesse, Humour"
                        },
                        new
                        {
                            Id = "4",
                            Description = "Un vaste choix de narrations graphiques, des super-héros aux récits autobiographiques.",
                            Nom = "Bandes dessinées"
                        },
                        new
                        {
                            Id = "5",
                            Description = "Découvrez les vies fascinantes des personnalités qui ont façonné le monde.",
                            Nom = "Biographie"
                        },
                        new
                        {
                            Id = "6",
                            Description = "Voyagez dans des mondes lointains avec des histoires intemporelles, des fables et des légendes.",
                            Nom = "Conte"
                        },
                        new
                        {
                            Id = "7",
                            Description = "Des recettes alléchantes aux guides sommeliers, découvrez les saveurs du monde.",
                            Nom = "Cuisine – Vin"
                        },
                        new
                        {
                            Id = "8",
                            Description = "Approfondissez votre compréhension des sociétés contemporaines et de leurs nuances culturelles.",
                            Nom = "Culture et Société"
                        },
                        new
                        {
                            Id = "9",
                            Description = "Des ressources pour les linguistes, les étudiants et les éternels apprenants.",
                            Nom = "Dictionnaire – Langues – Éducation"
                        },
                        new
                        {
                            Id = "10",
                            Description = "Engagez-vous dans des réflexions profondes et argumentatives sur des enjeux contemporains.",
                            Nom = "Essai"
                        },
                        new
                        {
                            Id = "11",
                            Description = "Explorez le monde naturel, de la canopée de la jungle aux profondeurs des océans.",
                            Nom = "Faune – Flore"
                        },
                        new
                        {
                            Id = "12",
                            Description = "Évadez-vous avec des guides de voyage et des récits d'aventuriers des quatre coins du monde.",
                            Nom = "Géographie – Voyage"
                        },
                        new
                        {
                            Id = "13",
                            Description = "Démystifiez le monde des affaires, la complexité économique et les arcanes du droit.",
                            Nom = "Gestion – Économie – droit"
                        },
                        new
                        {
                            Id = "14",
                            Description = "Conseils et astuces pour naviguer dans la vie quotidienne, du bricolage à la gestion du temps.",
                            Nom = "Guide pratique"
                        },
                        new
                        {
                            Id = "15",
                            Description = "Immergez-vous dans les moments clés de l'histoire et les débats politiques actuels. ",
                            Nom = "Histoire"
                        },
                        new
                        {
                            Id = "16",
                            Description = "Pour un moment de détente, une collection de recueils drôles et de satires.",
                            Nom = "Humour"
                        },
                        new
                        {
                            Id = "17",
                            Description = "Restez à la pointe de la technologie avec des guides sur les logiciels, le codage et les innovations numériques.",
                            Nom = "Informatique"
                        },
                        new
                        {
                            Id = "18",
                            Description = "Une riche collection de classiques et de nouvelles œuvres, pour les amateurs de belle lettre.",
                            Nom = "Littérature"
                        },
                        new
                        {
                            Id = "19",
                            Description = "Inspirez-vous pour votre prochaine aventure, qu'elle soit en pleine nature ou dans une métropole animée.",
                            Nom = "Loisir, Tourisme, Nature"
                        },
                        new
                        {
                            Id = "20",
                            Description = "Des ressources pour les parents et ceux qui aspirent à le devenir, pour une vie familiale épanouie.",
                            Nom = "Maternité – Famille"
                        },
                        new
                        {
                            Id = "21",
                            Description = "Laissez-vous emporter par le rythme des vers, l'intensité du théâtre et la profondeur des essais.",
                            Nom = "Poésie – Théâtre – Essais"
                        },
                        new
                        {
                            Id = "22",
                            Description = "omprenez mieux la complexité de l'esprit humain et les clés d'une vie saine.",
                            Nom = "Psychologie – Santé"
                        },
                        new
                        {
                            Id = "23",
                            Description = "Explorez les croyances spirituelles du monde entier, des textes sacrés aux mystères ésotériques.",
                            Nom = "Religion – Ésotérisme"
                        },
                        new
                        {
                            Id = "24",
                            Description = "Voyagez dans des mondes parallèles, où l'imaginaire rencontre souvent la réflexion profonde.",
                            Nom = "Roman de science-fiction et fantastique"
                        },
                        new
                        {
                            Id = "25",
                            Description = "Des romans venus de France et d'ailleurs pour vous transporter dans de multiples univers narratifs.",
                            Nom = "Roman français et étranger "
                        },
                        new
                        {
                            Id = "26",
                            Description = "Plongez dans des enquêtes palpitantes, des énigmes à résoudre et des mystères à élucider.",
                            Nom = "Roman policier"
                        },
                        new
                        {
                            Id = "27",
                            Description = "Découvrez la richesse de la littérature québécoise, avec ses voix uniques et ses paysages envoûtants.",
                            Nom = "Roman québécois"
                        },
                        new
                        {
                            Id = "28",
                            Description = "Éclairez votre curiosité avec des textes scientifiques accessibles et informatifs.",
                            Nom = "Savoir Sciences"
                        },
                        new
                        {
                            Id = "29",
                            Description = "De la biologie à la physique, découvrez les dernières découvertes et théories.",
                            Nom = "Sciences"
                        },
                        new
                        {
                            Id = "30",
                            Description = "Des textes éclairants pour comprendre et explorer la diversité de la sexualité humaine.",
                            Nom = "Sexualité"
                        },
                        new
                        {
                            Id = "31",
                            Description = "Pour les passionnés de sport et les chercheurs d'activités, des histoires inspirantes aux guides pratiques.",
                            Nom = "Sport"
                        },
                        new
                        {
                            Id = "Sous-Catégorie Excel 43-1",
                            Description = "",
                            Nom = "Famille",
                            ParentId = "Excel 43"
                        },
                        new
                        {
                            Id = "Sous-Catégorie 7-1",
                            Description = "",
                            Nom = "Vin",
                            ParentId = "7"
                        },
                        new
                        {
                            Id = "Sous-Catégorie 9-1",
                            Description = "",
                            Nom = "Langues",
                            ParentId = "9"
                        },
                        new
                        {
                            Id = "Sous-Catégorie 9-2",
                            Description = "",
                            Nom = "Éducation",
                            ParentId = "9"
                        },
                        new
                        {
                            Id = "Sous-Catégorie 11-1",
                            Description = "",
                            Nom = "Flore",
                            ParentId = "11"
                        },
                        new
                        {
                            Id = "Sous-Catégorie 12-1",
                            Description = "",
                            Nom = "Voyage",
                            ParentId = "12"
                        },
                        new
                        {
                            Id = "Sous-Catégorie 13-1",
                            Description = "",
                            Nom = "Économie",
                            ParentId = "13"
                        },
                        new
                        {
                            Id = "Sous-Catégorie 13-2",
                            Description = "",
                            Nom = "droit",
                            ParentId = "13"
                        },
                        new
                        {
                            Id = "Sous-Catégorie 15-1",
                            Description = "",
                            Nom = "Politique",
                            ParentId = "15"
                        },
                        new
                        {
                            Id = "Sous-Catégorie 20-1",
                            Description = "",
                            Nom = "Famille",
                            ParentId = "20"
                        },
                        new
                        {
                            Id = "Sous-Catégorie 21-1",
                            Description = "",
                            Nom = "Théâtre",
                            ParentId = "21"
                        },
                        new
                        {
                            Id = "Sous-Catégorie 21-2",
                            Description = "",
                            Nom = "Essais",
                            ParentId = "21"
                        },
                        new
                        {
                            Id = "Sous-Catégorie 22-1",
                            Description = "",
                            Nom = "Santé",
                            ParentId = "22"
                        },
                        new
                        {
                            Id = "Sous-Catégorie 23-1",
                            Description = "",
                            Nom = "Ésotérisme",
                            ParentId = "23"
                        },
                        new
                        {
                            Id = "Sous-Catégorie 31-1",
                            Description = "",
                            Nom = "Loisirs",
                            ParentId = "31"
                        });
                });

            modelBuilder.Entity("VLISSIDES.Models.Commande", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AdresseId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("DateCommande")
                        .HasColumnType("datetime2");

                    b.Property<string>("MembreId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("PrixTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("StatutCommandeId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("AdresseId");

                    b.HasIndex("MembreId");

                    b.HasIndex("StatutCommandeId");

                    b.ToTable("Commandes");
                });

            modelBuilder.Entity("VLISSIDES.Models.Evaluation", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Commentaire")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateEvaluation")
                        .HasColumnType("datetime2");

                    b.Property<string>("LivreId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MembreId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Note")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LivreId");

                    b.HasIndex("MembreId");

                    b.ToTable("Evaluations");
                });

            modelBuilder.Entity("VLISSIDES.Models.Evenement", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("DateDebut")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateFin")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Evenements");
                });

            modelBuilder.Entity("VLISSIDES.Models.Favori", b =>
                {
                    b.Property<string>("MembreId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LivreId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("MembreId", "LivreId");

                    b.HasIndex("LivreId");

                    b.ToTable("Favoris");
                });

            modelBuilder.Entity("VLISSIDES.Models.Langue", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Langues", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "1",
                            Code = "fr",
                            Nom = "Français"
                        },
                        new
                        {
                            Id = "2",
                            Code = "en",
                            Nom = "Anglais"
                        });
                });

            modelBuilder.Entity("VLISSIDES.Models.Livre", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CommandeId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Couverture")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateAjout")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DatePublication")
                        .HasColumnType("datetime2");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LangueId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaisonEditionId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("NbExemplaires")
                        .HasColumnType("int");

                    b.Property<int>("NbPages")
                        .HasColumnType("int");

                    b.Property<string>("Resume")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CommandeId");

                    b.HasIndex("LangueId");

                    b.HasIndex("MaisonEditionId");

                    b.ToTable("Livres", (string)null);
                });

            modelBuilder.Entity("VLISSIDES.Models.LivreAuteur", b =>
                {
                    b.Property<string>("LivreId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AuteurId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LivreId", "AuteurId");

                    b.HasIndex("AuteurId");

                    b.ToTable("LivreAuteurs");
                });

            modelBuilder.Entity("VLISSIDES.Models.LivreCategorie", b =>
                {
                    b.Property<string>("LivreId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CategorieId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LivreId", "CategorieId");

                    b.HasIndex("CategorieId");

                    b.ToTable("LivreCategories");
                });

            modelBuilder.Entity("VLISSIDES.Models.LivreCommande", b =>
                {
                    b.Property<string>("LivreId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CommandeId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Quantite")
                        .HasColumnType("int");

                    b.HasKey("LivreId", "CommandeId");

                    b.HasIndex("CommandeId");

                    b.ToTable("LivreCommandes");
                });

            modelBuilder.Entity("VLISSIDES.Models.LivreTypeLivre", b =>
                {
                    b.Property<string>("LivreId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TypeLivreId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("Prix")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("LivreId", "TypeLivreId");

                    b.HasIndex("TypeLivreId");

                    b.ToTable("LivreTypeLivres");
                });

            modelBuilder.Entity("VLISSIDES.Models.MaisonEdition", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MaisonEditions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "Excel 1",
                            Nom = "Gallimard"
                        },
                        new
                        {
                            Id = "Excel 2",
                            Nom = "Gallimard Jeunesse"
                        },
                        new
                        {
                            Id = "Excel 3",
                            Nom = "Secker and Warburg"
                        },
                        new
                        {
                            Id = "Excel 4",
                            Nom = "Christian Bourgois Éditeur"
                        },
                        new
                        {
                            Id = "Excel 5",
                            Nom = "Grasset"
                        },
                        new
                        {
                            Id = "Excel 6",
                            Nom = "Penguin Classics"
                        },
                        new
                        {
                            Id = "Excel 7",
                            Nom = "Gallimard"
                        },
                        new
                        {
                            Id = "Excel 8",
                            Nom = "Penguin Classics"
                        },
                        new
                        {
                            Id = "Excel 9",
                            Nom = "Le Livre de Poche"
                        },
                        new
                        {
                            Id = "Excel 10",
                            Nom = "Folio"
                        },
                        new
                        {
                            Id = "Excel 11",
                            Nom = "Gallimard"
                        },
                        new
                        {
                            Id = "Excel 12",
                            Nom = "Albin Michel"
                        },
                        new
                        {
                            Id = "Excel 13",
                            Nom = "Penguin Classics"
                        },
                        new
                        {
                            Id = "Excel 14",
                            Nom = "Le Livre de Poche"
                        },
                        new
                        {
                            Id = "Excel 15",
                            Nom = "Le Livre de Poche"
                        },
                        new
                        {
                            Id = "Excel 16",
                            Nom = "Pocket"
                        },
                        new
                        {
                            Id = "Excel 17",
                            Nom = "Gallimard"
                        },
                        new
                        {
                            Id = "Excel 18",
                            Nom = "Gallimard"
                        },
                        new
                        {
                            Id = "Excel 19",
                            Nom = "Plume de Paon"
                        },
                        new
                        {
                            Id = "Excel 20",
                            Nom = "Le Livre de Poche"
                        },
                        new
                        {
                            Id = "Excel 21",
                            Nom = "Folio"
                        },
                        new
                        {
                            Id = "Excel 22",
                            Nom = "Flammarion"
                        },
                        new
                        {
                            Id = "Excel 23",
                            Nom = "Folio"
                        },
                        new
                        {
                            Id = "Excel 24",
                            Nom = "Belfond"
                        },
                        new
                        {
                            Id = "Excel 25",
                            Nom = "Pocket"
                        },
                        new
                        {
                            Id = "Excel 26",
                            Nom = "Flammarion"
                        },
                        new
                        {
                            Id = "Excel 27",
                            Nom = "Livre de Poche Classiques"
                        },
                        new
                        {
                            Id = "Excel 28",
                            Nom = "Le Livre de Poche"
                        },
                        new
                        {
                            Id = "Excel 29",
                            Nom = "Christian Bourgois Éditeur"
                        },
                        new
                        {
                            Id = "Excel 30",
                            Nom = "Le Livre de Poche"
                        },
                        new
                        {
                            Id = "Excel 31",
                            Nom = "Belfond"
                        },
                        new
                        {
                            Id = "Excel 32",
                            Nom = "Le Livre de Poche"
                        },
                        new
                        {
                            Id = "Excel 33",
                            Nom = "Camion Blanc"
                        },
                        new
                        {
                            Id = "Excel 34",
                            Nom = "Le Livre de Poche"
                        },
                        new
                        {
                            Id = "Excel 35",
                            Nom = "Gallimard"
                        },
                        new
                        {
                            Id = "Excel 36",
                            Nom = "Gallimard"
                        },
                        new
                        {
                            Id = "Excel 37",
                            Nom = "Le Livre de Poche"
                        },
                        new
                        {
                            Id = "Excel 38",
                            Nom = "Flammarion"
                        },
                        new
                        {
                            Id = "Excel 39",
                            Nom = "Le Livre de Poche"
                        },
                        new
                        {
                            Id = "Excel 40",
                            Nom = "Folio Junior"
                        },
                        new
                        {
                            Id = "Excel 42",
                            Nom = "Les Arènes"
                        },
                        new
                        {
                            Id = "Excel 43",
                            Nom = "Actes Sud"
                        },
                        new
                        {
                            Id = "Excel 44",
                            Nom = "Eyrolles"
                        },
                        new
                        {
                            Id = "Excel 45",
                            Nom = "Nathan"
                        },
                        new
                        {
                            Id = "Excel 46",
                            Nom = "Eyrolles"
                        },
                        new
                        {
                            Id = "Excel 48",
                            Nom = "Hachette"
                        },
                        new
                        {
                            Id = "Excel 49",
                            Nom = "Casterman"
                        },
                        new
                        {
                            Id = "Excel 50",
                            Nom = "Flammarion"
                        },
                        new
                        {
                            Id = "Excel 51",
                            Nom = "L'Association"
                        },
                        new
                        {
                            Id = "Excel 52",
                            Nom = "DC Comics"
                        },
                        new
                        {
                            Id = "0",
                            Nom = "Maison d'édition par défaut"
                        });
                });

            modelBuilder.Entity("VLISSIDES.Models.Promotions", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("DateDebut")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateFin")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LivreId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Rabais")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Promotions");
                });

            modelBuilder.Entity("VLISSIDES.Models.Reservation", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("DateReservation")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EvenementId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MembreId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("EvenementId");

                    b.HasIndex("MembreId");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("VLISSIDES.Models.StatutCommande", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("StatutCommande", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "1",
                            Nom = "En attente"
                        },
                        new
                        {
                            Id = "2",
                            Nom = "En cours de traitement"
                        },
                        new
                        {
                            Id = "3",
                            Nom = "En cours de livraison"
                        },
                        new
                        {
                            Id = "4",
                            Nom = "Livrée"
                        },
                        new
                        {
                            Id = "5",
                            Nom = "Annulée"
                        });
                });

            modelBuilder.Entity("VLISSIDES.Models.TypeLivre", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Prix")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("TypeLivres", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "Papier Excel 1",
                            Nom = "Papier",
                            Prix = 22.25
                        },
                        new
                        {
                            Id = "Papier Excel 2",
                            Nom = "Papier",
                            Prix = 32.75
                        },
                        new
                        {
                            Id = "Numérique Excel 2",
                            Nom = "Numérique",
                            Prix = 30.0
                        },
                        new
                        {
                            Id = "Papier Excel 3",
                            Nom = "Papier",
                            Prix = 18.0
                        },
                        new
                        {
                            Id = "Papier Excel 4",
                            Nom = "Papier",
                            Prix = 29.0
                        },
                        new
                        {
                            Id = "Numérique Excel 4",
                            Nom = "Numérique",
                            Prix = 27.0
                        },
                        new
                        {
                            Id = "Papier Excel 5",
                            Nom = "Papier",
                            Prix = 19.5
                        },
                        new
                        {
                            Id = "Papier Excel 6",
                            Nom = "Papier",
                            Prix = 18.75
                        },
                        new
                        {
                            Id = "Papier Excel 7",
                            Nom = "Papier",
                            Prix = 15.0
                        },
                        new
                        {
                            Id = "Papier Excel 8",
                            Nom = "Papier",
                            Prix = 21.25
                        },
                        new
                        {
                            Id = "Papier Excel 9",
                            Nom = "Papier",
                            Prix = 9.75
                        },
                        new
                        {
                            Id = "Papier Excel 10",
                            Nom = "Papier",
                            Prix = 32.0
                        },
                        new
                        {
                            Id = "Numérique Excel 10",
                            Nom = "Numérique",
                            Prix = 22.0
                        },
                        new
                        {
                            Id = "Papier Excel 11",
                            Nom = "Papier",
                            Prix = 28.0
                        },
                        new
                        {
                            Id = "Papier Excel 12",
                            Nom = "Papier",
                            Prix = 26.0
                        },
                        new
                        {
                            Id = "Numérique Excel 12",
                            Nom = "Numérique",
                            Prix = 20.0
                        },
                        new
                        {
                            Id = "Papier Excel 13",
                            Nom = "Papier",
                            Prix = 22.0
                        },
                        new
                        {
                            Id = "Numérique Excel 13",
                            Nom = "Numérique",
                            Prix = 18.0
                        },
                        new
                        {
                            Id = "Papier Excel 14",
                            Nom = "Papier",
                            Prix = 13.0
                        },
                        new
                        {
                            Id = "Papier Excel 15",
                            Nom = "Papier",
                            Prix = 24.0
                        },
                        new
                        {
                            Id = "Numérique Excel 15",
                            Nom = "Numérique",
                            Prix = 22.0
                        },
                        new
                        {
                            Id = "Papier Excel 16",
                            Nom = "Papier",
                            Prix = 18.0
                        },
                        new
                        {
                            Id = "Numérique Excel 16",
                            Nom = "Numérique",
                            Prix = 14.0
                        },
                        new
                        {
                            Id = "Papier Excel 17",
                            Nom = "Papier",
                            Prix = 30.0
                        },
                        new
                        {
                            Id = "Papier Excel 18",
                            Nom = "Papier",
                            Prix = 18.0
                        },
                        new
                        {
                            Id = "Papier Excel 19",
                            Nom = "Papier",
                            Prix = 25.0
                        },
                        new
                        {
                            Id = "Papier Excel 20",
                            Nom = "Papier",
                            Prix = 19.75
                        },
                        new
                        {
                            Id = "Papier Excel 21",
                            Nom = "Papier",
                            Prix = 22.0
                        },
                        new
                        {
                            Id = "Papier Excel 22",
                            Nom = "Papier",
                            Prix = 31.5
                        },
                        new
                        {
                            Id = "Numérique Excel 22",
                            Nom = "Numérique",
                            Prix = 31.5
                        },
                        new
                        {
                            Id = "Papier Excel 23",
                            Nom = "Papier",
                            Prix = 24.75
                        },
                        new
                        {
                            Id = "Numérique Excel 23",
                            Nom = "Numérique",
                            Prix = 24.75
                        },
                        new
                        {
                            Id = "Papier Excel 24",
                            Nom = "Papier",
                            Prix = 18.25
                        },
                        new
                        {
                            Id = "Numérique Excel 24",
                            Nom = "Numérique",
                            Prix = 15.0
                        },
                        new
                        {
                            Id = "Papier Excel 25",
                            Nom = "Papier",
                            Prix = 26.0
                        },
                        new
                        {
                            Id = "Numérique Excel 25",
                            Nom = "Numérique",
                            Prix = 20.0
                        },
                        new
                        {
                            Id = "Papier Excel 26",
                            Nom = "Papier",
                            Prix = 18.0
                        },
                        new
                        {
                            Id = "Papier Excel 27",
                            Nom = "Papier",
                            Prix = 21.0
                        },
                        new
                        {
                            Id = "Papier Excel 28",
                            Nom = "Papier",
                            Prix = 17.0
                        },
                        new
                        {
                            Id = "Papier Excel 29",
                            Nom = "Papier",
                            Prix = 36.0
                        },
                        new
                        {
                            Id = "Numérique Excel 29",
                            Nom = "Numérique",
                            Prix = 32.0
                        },
                        new
                        {
                            Id = "Papier Excel 30",
                            Nom = "Papier",
                            Prix = 15.0
                        },
                        new
                        {
                            Id = "Papier Excel 31",
                            Nom = "Papier",
                            Prix = 16.0
                        },
                        new
                        {
                            Id = "Papier Excel 32",
                            Nom = "Papier",
                            Prix = 21.0
                        },
                        new
                        {
                            Id = "Papier Excel 33",
                            Nom = "Papier",
                            Prix = 22.0
                        },
                        new
                        {
                            Id = "Papier Excel 34",
                            Nom = "Papier",
                            Prix = 19.5
                        },
                        new
                        {
                            Id = "Papier Excel 35",
                            Nom = "Papier",
                            Prix = 24.0
                        },
                        new
                        {
                            Id = "Papier Excel 36",
                            Nom = "Papier",
                            Prix = 32.0
                        },
                        new
                        {
                            Id = "Numérique Excel 36",
                            Nom = "Numérique",
                            Prix = 24.0
                        },
                        new
                        {
                            Id = "Papier Excel 37",
                            Nom = "Papier",
                            Prix = 36.0
                        },
                        new
                        {
                            Id = "Numérique Excel 37",
                            Nom = "Numérique",
                            Prix = 28.0
                        },
                        new
                        {
                            Id = "Papier Excel 38",
                            Nom = "Papier",
                            Prix = 28.0
                        },
                        new
                        {
                            Id = "Numérique Excel 38",
                            Nom = "Numérique",
                            Prix = 20.0
                        },
                        new
                        {
                            Id = "Papier Excel 39",
                            Nom = "Papier",
                            Prix = 29.0
                        },
                        new
                        {
                            Id = "Numérique Excel 39",
                            Nom = "Numérique",
                            Prix = 22.0
                        },
                        new
                        {
                            Id = "Papier Excel 40",
                            Nom = "Papier",
                            Prix = 18.0
                        },
                        new
                        {
                            Id = "Numérique Excel 40",
                            Nom = "Numérique",
                            Prix = 12.0
                        },
                        new
                        {
                            Id = "Papier Excel 42",
                            Nom = "Papier",
                            Prix = 64.0
                        },
                        new
                        {
                            Id = "Numérique Excel 42",
                            Nom = "Numérique",
                            Prix = 50.0
                        },
                        new
                        {
                            Id = "Papier Excel 43",
                            Nom = "Papier",
                            Prix = 21.0
                        },
                        new
                        {
                            Id = "Numérique Excel 43",
                            Nom = "Numérique",
                            Prix = 21.0
                        },
                        new
                        {
                            Id = "Papier Excel 44",
                            Nom = "Papier",
                            Prix = 50.0
                        },
                        new
                        {
                            Id = "Numérique Excel 44",
                            Nom = "Numérique",
                            Prix = 48.0
                        },
                        new
                        {
                            Id = "Papier Excel 45",
                            Nom = "Papier",
                            Prix = 36.0
                        },
                        new
                        {
                            Id = "Numérique Excel 45",
                            Nom = "Numérique",
                            Prix = 30.0
                        },
                        new
                        {
                            Id = "Papier Excel 46",
                            Nom = "Papier",
                            Prix = 25.0
                        },
                        new
                        {
                            Id = "Numérique Excel 46",
                            Nom = "Numérique",
                            Prix = 25.0
                        },
                        new
                        {
                            Id = "Papier Excel 48",
                            Nom = "Papier",
                            Prix = 28.0
                        },
                        new
                        {
                            Id = "Papier Excel 49",
                            Nom = "Papier",
                            Prix = 26.0
                        },
                        new
                        {
                            Id = "Papier Excel 50",
                            Nom = "Papier",
                            Prix = 24.0
                        },
                        new
                        {
                            Id = "Papier Excel 51",
                            Nom = "Papier",
                            Prix = 32.0
                        },
                        new
                        {
                            Id = "Papier Excel 52",
                            Nom = "Papier",
                            Prix = 31.0
                        });
                });

            modelBuilder.Entity("VLISSIDES.Models.Employe", b =>
                {
                    b.HasBaseType("VLISSIDES.Models.ApplicationUser");

                    b.Property<string>("NoEmploye")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Employe");

                    b.HasData(
                        new
                        {
                            Id = "1",
                            AccessFailedCount = 0,
                            AdressePrincipaleId = "",
                            ConcurrencyStamp = "d094ebfd-565f-4725-8ccf-a235ee584ae3",
                            Email = "employe@employe.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Nom = "EMPLOYE",
                            NormalizedEmail = "EMPLOYE@EMPLOYE.COM",
                            NormalizedUserName = "EMPLOYE@EMPLOYE.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEP5A0+Sh49GqZJZev/DKqD7yieTvqVejrmGV0mV6PL5KNos4tLJnJL1tHceX7HezGA==",
                            PhoneNumberConfirmed = false,
                            Prenom = "Employe",
                            SecurityStamp = "e26736a3-d203-4d6d-bf87-065ab4ea1ced",
                            TwoFactorEnabled = false,
                            UserName = "employe@employe.com",
                            NoEmploye = "007"
                        });
                });

            modelBuilder.Entity("VLISSIDES.Models.Membre", b =>
                {
                    b.HasBaseType("VLISSIDES.Models.ApplicationUser");

                    b.Property<string>("CommandeId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateAdhesion")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoMembre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReservationId")
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Membre");

                    b.HasData(
                        new
                        {
                            Id = "2",
                            AccessFailedCount = 0,
                            AdressePrincipaleId = "",
                            ConcurrencyStamp = "a8f7e6d7-5fe6-4012-bd5b-f0629e0061ff",
                            Email = "membre@membre.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Nom = "MEMBRE",
                            NormalizedEmail = "MEMBRE@MEMBRE.COM",
                            NormalizedUserName = "MEMBRE@MEMBRE.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEP5A0+Sh49GqZJZev/DKqD7yieTvqVejrmGV0mV6PL5KNos4tLJnJL1tHceX7HezGA==",
                            PhoneNumberConfirmed = false,
                            Prenom = "Membre",
                            SecurityStamp = "f3f6f01d-ad72-44d4-a852-1c16a0146b3f",
                            TwoFactorEnabled = false,
                            UserName = "membre@membre.com",
                            DateAdhesion = new DateTime(2023, 10, 4, 16, 49, 19, 965, DateTimeKind.Local).AddTicks(8048),
                            NoMembre = "123456"
                        });
                });

            modelBuilder.Entity("LivrePromotions", b =>
                {
                    b.HasOne("VLISSIDES.Models.Livre", null)
                        .WithMany()
                        .HasForeignKey("LivresId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VLISSIDES.Models.Promotions", null)
                        .WithMany()
                        .HasForeignKey("PromotionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("VLISSIDES.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("VLISSIDES.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VLISSIDES.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("VLISSIDES.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VLISSIDES.Models.Adresse", b =>
                {
                    b.HasOne("VLISSIDES.Models.ApplicationUser", null)
                        .WithMany("AdressesLivraison")
                        .HasForeignKey("ApplicationUserId");
                });

            modelBuilder.Entity("VLISSIDES.Models.ApplicationUser", b =>
                {
                    b.HasOne("VLISSIDES.Models.Adresse", "AdressePrincipale")
                        .WithMany()
                        .HasForeignKey("AdressePrincipaleId");

                    b.Navigation("AdressePrincipale");
                });

            modelBuilder.Entity("VLISSIDES.Models.Categorie", b =>
                {
                    b.HasOne("VLISSIDES.Models.Categorie", "Parent")
                        .WithMany("Enfants")
                        .HasForeignKey("ParentId");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("VLISSIDES.Models.Commande", b =>
                {
                    b.HasOne("VLISSIDES.Models.Adresse", "AdresseLivraison")
                        .WithMany()
                        .HasForeignKey("AdresseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VLISSIDES.Models.Membre", "Membre")
                        .WithMany("Commandes")
                        .HasForeignKey("MembreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VLISSIDES.Models.StatutCommande", null)
                        .WithMany("Commandes")
                        .HasForeignKey("StatutCommandeId");

                    b.Navigation("AdresseLivraison");

                    b.Navigation("Membre");
                });

            modelBuilder.Entity("VLISSIDES.Models.Evaluation", b =>
                {
                    b.HasOne("VLISSIDES.Models.Livre", "Livre")
                        .WithMany("Evaluations")
                        .HasForeignKey("LivreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VLISSIDES.Models.Membre", "Membre")
                        .WithMany()
                        .HasForeignKey("MembreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Livre");

                    b.Navigation("Membre");
                });

            modelBuilder.Entity("VLISSIDES.Models.Favori", b =>
                {
                    b.HasOne("VLISSIDES.Models.Livre", "Livre")
                        .WithMany("Favoris")
                        .HasForeignKey("LivreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VLISSIDES.Models.Membre", "Membre")
                        .WithMany("Favoris")
                        .HasForeignKey("MembreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Livre");

                    b.Navigation("Membre");
                });

            modelBuilder.Entity("VLISSIDES.Models.Livre", b =>
                {
                    b.HasOne("VLISSIDES.Models.Commande", null)
                        .WithMany("Livres")
                        .HasForeignKey("CommandeId");

                    b.HasOne("VLISSIDES.Models.Langue", "Langue")
                        .WithMany("Livres")
                        .HasForeignKey("LangueId");

                    b.HasOne("VLISSIDES.Models.MaisonEdition", "MaisonEdition")
                        .WithMany("Livres")
                        .HasForeignKey("MaisonEditionId");

                    b.Navigation("Langue");

                    b.Navigation("MaisonEdition");
                });

            modelBuilder.Entity("VLISSIDES.Models.LivreAuteur", b =>
                {
                    b.HasOne("VLISSIDES.Models.Auteur", "Auteur")
                        .WithMany("Livres")
                        .HasForeignKey("AuteurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VLISSIDES.Models.Livre", "Livre")
                        .WithMany("LivreAuteurs")
                        .HasForeignKey("LivreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Auteur");

                    b.Navigation("Livre");
                });

            modelBuilder.Entity("VLISSIDES.Models.LivreCategorie", b =>
                {
                    b.HasOne("VLISSIDES.Models.Categorie", "Categorie")
                        .WithMany("Livres")
                        .HasForeignKey("CategorieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VLISSIDES.Models.Livre", "Livre")
                        .WithMany("LivreCategories")
                        .HasForeignKey("LivreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categorie");

                    b.Navigation("Livre");
                });

            modelBuilder.Entity("VLISSIDES.Models.LivreCommande", b =>
                {
                    b.HasOne("VLISSIDES.Models.Commande", "Commande")
                        .WithMany("LivreCommandes")
                        .HasForeignKey("CommandeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VLISSIDES.Models.Livre", "Livre")
                        .WithMany("LivreCommandes")
                        .HasForeignKey("LivreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Commande");

                    b.Navigation("Livre");
                });

            modelBuilder.Entity("VLISSIDES.Models.LivreTypeLivre", b =>
                {
                    b.HasOne("VLISSIDES.Models.Livre", "Livre")
                        .WithMany("LivreTypeLivres")
                        .HasForeignKey("LivreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VLISSIDES.Models.TypeLivre", "TypeLivre")
                        .WithMany("TypeLivres")
                        .HasForeignKey("TypeLivreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Livre");

                    b.Navigation("TypeLivre");
                });

            modelBuilder.Entity("VLISSIDES.Models.Reservation", b =>
                {
                    b.HasOne("VLISSIDES.Models.Evenement", "Evenement")
                        .WithMany("Reservations")
                        .HasForeignKey("EvenementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VLISSIDES.Models.Membre", "Membre")
                        .WithMany("Reservations")
                        .HasForeignKey("MembreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Evenement");

                    b.Navigation("Membre");
                });

            modelBuilder.Entity("VLISSIDES.Models.ApplicationUser", b =>
                {
                    b.Navigation("AdressesLivraison");
                });

            modelBuilder.Entity("VLISSIDES.Models.Auteur", b =>
                {
                    b.Navigation("Livres");
                });

            modelBuilder.Entity("VLISSIDES.Models.Categorie", b =>
                {
                    b.Navigation("Enfants");

                    b.Navigation("Livres");
                });

            modelBuilder.Entity("VLISSIDES.Models.Commande", b =>
                {
                    b.Navigation("LivreCommandes");

                    b.Navigation("Livres");
                });

            modelBuilder.Entity("VLISSIDES.Models.Evenement", b =>
                {
                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("VLISSIDES.Models.Langue", b =>
                {
                    b.Navigation("Livres");
                });

            modelBuilder.Entity("VLISSIDES.Models.Livre", b =>
                {
                    b.Navigation("Evaluations");

                    b.Navigation("Favoris");

                    b.Navigation("LivreAuteurs");

                    b.Navigation("LivreCategories");

                    b.Navigation("LivreCommandes");

                    b.Navigation("LivreTypeLivres");
                });

            modelBuilder.Entity("VLISSIDES.Models.MaisonEdition", b =>
                {
                    b.Navigation("Livres");
                });

            modelBuilder.Entity("VLISSIDES.Models.StatutCommande", b =>
                {
                    b.Navigation("Commandes");
                });

            modelBuilder.Entity("VLISSIDES.Models.TypeLivre", b =>
                {
                    b.Navigation("TypeLivres");
                });

            modelBuilder.Entity("VLISSIDES.Models.Membre", b =>
                {
                    b.Navigation("Commandes");

                    b.Navigation("Favoris");

                    b.Navigation("Reservations");
                });
#pragma warning restore 612, 618
        }
    }
}
